apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: observability
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus-svc.observability.svc.wsc2026.skills.local:9090
      isDefault: true
    - name: Alertmanager
      type: alertmanager
      access: proxy
      url: http://alertmanager-svc.observability.svc.wsc2026.skills.local:9093
      jsonData:
        implementation: prometheus
        handleGrafanaManagedAlerts: false
    - name: CloudWatch
      type: cloudwatch
      jsonData:
        authType: default
        defaultRegion: ap-northeast-2
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-sa
  namespace: observability
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      serviceAccountName: grafana-sa
      nodeSelector:
        wsc2026/node: addon
      containers:
      - name: grafana
        image: grafana/grafana:13.0.6
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "Skills$#$@!"
        volumeMounts:
        - name: datasources
          mountPath: /etc/grafana/provisioning/datasources
      volumes:
      - name: datasources
        configMap:
          name: grafana-datasources
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  namespace: observability
  annotations:
   service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: grafana