apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-cluster-info
  namespace: amazon-cloudwatch
data:
  cluster.name: "unicorn-eks-cluster"
  logs.region: "ap-northeast-2"
  http.server: "On"
  http.port: "2020"
  read.head: "Off"
  read.tail: "On"
