apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: monitoring
data:
  loki.yaml: |
    auth_enabled: false
    server:
      http_listen_port: 3100
    common:
      ring:
        instance_addr: 127.0.0.1
        kvstore:
          store: inmemory
      replication_factor: 1
      path_prefix: /tmp/loki
    schema_config:
      configs:
        - from: 2024-01-01
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h
    storage_config:
      filesystem:
        directory: /tmp/loki/chunks
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: o11y-loki
  namespace: monitoring
spec:
  serviceName: o11y-loki
  replicas: 1
  selector:
    matchLabels:
      app: o11y-loki
  template:
    metadata:
      labels:
        app: o11y-loki
    spec:
      initContainers:
      - name: chmod-pv
        image: busybox:1.36
        command: ["sh", "-c", "chown -R 10001:10001 /tmp/loki && chmod -R 777 /tmp/loki"]
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: storage
          mountPath: /tmp/loki
      containers:
      - name: loki
        image: grafana/loki:3.7.6
        args:
        - -config.file=/etc/loki/loki.yaml
        ports:
        - containerPort: 3100
          name: http
        - containerPort: 4318
          name: otlp-http
        volumeMounts:
        - name: config
          mountPath: /etc/loki
        - name: storage
          mountPath: /tmp/loki
      volumes:
      - name: config
        configMap:
          name: loki-config
  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: manual
      resources:
        requests:
          storage: 10Gi
