apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqs-worker
  namespace: skills-sqs
  labels:
    app: sqs-worker
spec:
  replicas: 0
  selector:
    matchLabels:
      app: sqs-worker
  template:
    metadata:
      labels:
        app: sqs-worker
    spec:
      serviceAccountName: sqs-worker-sa
      nodeSelector:
        karpenter.sh/nodepool: skills-sqs-nodepool
        skills-nodepool: event-worker
      containers:
        - name: worker
          image: 602620439352.dkr.ecr.us-west-2.amazonaws.com/worker:latest
          env:
            - name: SQS_QUEUE_URL
              value: "https://sqs.us-west-2.amazonaws.com/602620439352/skills-sqs-queue"
            - name: AWS_REGION
              value: "us-west-2"
            - name: PROCESSING_SECONDS
              value: "5"
